name: tests

on:
  push:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    name: Jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Run stock:now command
        run: php pastock stock:now

      - name: Run stock:query command
        run: php pastock stock:query 2330
