name: tests

on: [ push, pull_request ]

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    name: PHP Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute phpcs
        run: php vendor/bin/phpcs

      - name: Execute tests
        run: phpdbg -qrr vendor/bin/phpunit

      - name: Test stock:now command to see 2330.TW
        run: php pastock stock:now 2330

      - name: Test stock:query command to see 2330.TW
        run: php pastock stock:query 2330
