name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    name: PHP Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute phpcs
        run: php vendor/bin/phpcs

      - name: Execute tests
        run: phpdbg -qrr vendor/bin/phpunit

      - name: Run stock:now command
        run: php artisan stock:now

      - name: Run stock:query command
        run: php artisan stock:query 2330

      - name: Run stock:pers command
        run: php artisan stock:pers --filter-per-lt=13 --filter-pbr-lt=0.7
